spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
     
     #define the Kafka topic name and the number of
     # messages to send every time we do an HTTP REST request. 
tpd:
  topic-name: advice-topic
  messages-per-request: 10
      
